"use client";
import{useEffect,useRef,useState}from"react";import"./style.css";
const SIZE=20,CELL=20;
export default function Home(){const canvasRef=useRef(null);const game=useRef({snake:[{x:10,y:10},{x:9,y:10},{x:8,y:10}],dir:{x:1,y:0},next:{x:1,y:0},food:{x:4,y:4},dead:false,paused:false});const[points,setPoints]=useState(0),[sats,setSats]=useState(0),[invoice,setInvoice]=useState(""),[message,setMessage]=useState("Apanha os quadrados. Cada um vale 10 pontos."),[withdrawing,setWithdrawing]=useState(false);
function draw(){const c=canvasRef.current;if(!c)return;const x=c.getContext("2d"),g=game.current;x.fillStyle="#0b1118";x.fillRect(0,0,400,400);x.strokeStyle="#16222d";for(let i=0;i<=SIZE;i++){x.beginPath();x.moveTo(i*CELL,0);x.lineTo(i*CELL,400);x.stroke();x.beginPath();x.moveTo(0,i*CELL);x.lineTo(400,i*CELL);x.stroke()}x.fillStyle="#ffb000";x.fillRect(g.food.x*CELL+3,g.food.y*CELL+3,14,14);g.snake.forEach((p,i)=>{x.fillStyle=i===0?"#9ff3c9":"#35b67f";x.fillRect(p.x*CELL+1,p.y*CELL+1,18,18)})}
function turn(x,y){const g=game.current;if(x===-g.dir.x&&y===-g.dir.y)return;g.next={x,y}}
function newFood(){const g=game.current;do{g.food={x:Math.floor(Math.random()*SIZE),y:Math.floor(Math.random()*SIZE)}}while(g.snake.some(p=>p.x===g.food.x&&p.y===g.food.y))}
function restart(){game.current={snake:[{x:10,y:10},{x:9,y:10},{x:8,y:10}],dir:{x:1,y:0},next:{x:1,y:0},food:{x:4,y:4},dead:false,paused:false};setPoints(0);setMessage("Novo jogo iniciado.");setTimeout(draw,0)}
function togglePause(){const g=game.current;if(g.dead)return;g.paused=!g.paused;setMessage(g.paused?"Jogo em pausa.":"Jogo retomado.")}
useEffect(()=>{const onKey=e=>{const m={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]};if(m[e.key]){e.preventDefault();turn(...m[e.key])}};window.addEventListener("keydown",onKey);const t=setInterval(()=>{const g=game.current;if(g.dead||g.paused)return;g.dir=g.next;const h={x:g.snake[0].x+g.dir.x,y:g.snake[0].y+g.dir.y};if(h.x<0||h.y<0||h.x>=SIZE||h.y>=SIZE||g.snake.some(p=>p.x===h.x&&p.y===h.y)){g.dead=true;setMessage("Fim do jogo. Carrega em Reiniciar.");return}g.snake.unshift(h);if(h.x===g.food.x&&h.y===g.food.y){setPoints(v=>v+10);newFood()}else g.snake.pop();draw()},130);draw();return()=>{clearInterval(t);window.removeEventListener("keydown",onKey)}},[]);
function convert(){const a=Math.floor(points/100);if(a<1)return setMessage("Precisas de pelo menos 100 pontos.");setPoints(v=>v-a*100);setSats(v=>v+a);setMessage(`${a} sat convertido para o saldo do jogo ⚡`)}
async function withdraw(){if(withdrawing)return;if(!invoice.trim())return setMessage("Introduz uma invoice Lightning BOLT11.");if(sats<1)return setMessage("Ainda não tens sats suficientes.");try{setWithdrawing(true);setMessage("A processar pagamento Lightning...");const r=await fetch("/api/withdraw",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({invoice:invoice.trim(),amount:sats})});const d=await r.json();if(!r.ok)return setMessage(d.error||"Erro no pagamento.");if(d.pending)return setMessage("Pagamento iniciado e pendente ⚡");setMessage("Pagamento Lightning concluído ⚡");setSats(0);setInvoice("")}catch{setMessage("Não foi possível ligar ao backend BTCPay.")}finally{setWithdrawing(false)}}
return <main><header><div className="coin">₿</div><div><h1>Cobra Lightning</h1><p className="subtitle">Joga • acumula pontos • converte para sats</p></div></header><div className="stats"><div><span>PONTOS</span><strong>{points}</strong></div><div><span>SALDO</span><strong>{sats} sats</strong></div><div><span>TAXA</span><strong>100 = 1 sat</strong></div></div><canvas ref={canvasRef} width="400" height="400"/><p className="message">{message}</p><div className="pad"><button onClick={()=>turn(0,-1)}>↑</button><div><button onClick={()=>turn(-1,0)}>←</button><button onClick={()=>turn(0,1)}>↓</button><button onClick={()=>turn(1,0)}>→</button></div></div><div className="actions"><button onClick={togglePause}>⏸ Pausa</button><button onClick={restart}>↻ Reiniciar</button><button className="primary" onClick={convert}>⚡ Converter pontos</button></div><section><h2>Levantar sats ⚡</h2><textarea value={invoice} onChange={e=>setInvoice(e.target.value)} placeholder="Cole uma invoice Lightning BOLT11 (lnbc...)" rows={4}/><button className="primary full" onClick={withdraw} disabled={withdrawing}>{withdrawing?"A processar...":"Pagar invoice ⚡"}</button><small>BTCPay Server por baixo, usando variáveis LIGHTNING_*.</small></section></main>}
